### ISSUE TITLE
memory request doesn't support full 64-bit addresses

### ISSUE THREAD

**Issue by dschaefer** [eclipse-cdt/cdt-gdb-adapter#66]
I see we are using number for the arguments to the memoryRequest. Numbers in JavaScript are doubles and, as such, only support 53-bits of integer precision.

I've used the 'long' library in the past and it's pretty good. Though depending on what we need it for, we may just get away with our own { lsw: number, msw: number }.

**Comment by simark** [comment]
Oh, didn't know about that :(

**Comment by simark** [comment]
Actually, I was thinking about supporting arbitrary expressions (such as `&myvariable`) instead of just numerical addresses.  That would make the field a string, so bypass this problem.

**Comment by simark** [comment]
My vision is the the memory browser has a little "go to" input box, where you can type an address, or an expression.  When you press enter, it goes to that address (or the address resulting of that expression).  Even if the expression changes (because you are stepping the program, for example) the memory browser wouldn't change what address it shows (the contents could change though).  Only if you press enter again in the "go to" box would it try to update.

So it wouldn't be like the Expressions view, where expressions are re-evaluated constantly.

**Comment by dschaefer** [comment]
That's reasonable.

Another use case I'm thinking of is for viewing hardware registers. There may be multiple fixed addresses you want to look at that are memory mapped into the process's address space. Or for microcontrollers which don't have MMUs, they're just fixed addresses.

Now that could be solved by having multiple browsers open and just keeping them around.

Funny enought, the Eclipse plug-ins have both. The Memory Browser as a Go button and the Memory view has monitors at fixed addresses.

**Comment by dschaefer** [comment]
Yeah, playing with them in CDT, the Memory Browser feels easier to use. And it does keep a history of Go's which would solve my case too.

Interesting, looking at PlatformIO, it looks like it creates a view with a list of memory addresses and lengths and opens webviews to show the contents. This is more like Eclipse IDE's Memory view and where I started heading today. Need to step back and think about the most likely use cases.

**Comment by dschaefer** [comment]
And, anyway, this is more a discussion for the clients. We'll need to think what we want to do on the Eclipse IDE side too. Do we continue to support both, etc.
