### ISSUE TITLE
Usage of webpack

### ISSUE THREAD

**Issue by simark** [eclipse-cdt/cdt-gdb-adapter#7]
I have started to play with cdt-gdb-adapter, trying to integrate it with Theia (replace code-debug with it in https://github.com/eclipse/theia-cpp-extension/ ).

I was a bit surprised to see this project using webpack.  Since it is meant to be run in node, it is not necessary to bundle everything in a single js file.  If you are fine with it, I would suggest compiling each ts file to a js file (`src/foo.ts` -> `out/foo.js`).  The debug server can then be started by invoking `out/debugAdapter.js`.  If somebody really wants a single-file (for example, because it facilitates distribution), we can add a further webpack pass.

I have it working locally, I can open a PR about it if this is ok with you.

**Comment by dschaefer** [comment]
There's ways to tweak webpack to not include stuff. I'd have to see the implementation of getPath to understand how it works and what we could do.

**Comment by simark** [comment]
> There's ways to tweak webpack to not include stuff. I'd have to see the implementation of getPath to understand how it works and what we could do.

But then, we would need to run tsc just for the files that are not included in the webpack.  It seems much simpler to tsc everything, then webpack what needs to be bundled in the actual debug adapter binary.

The `getPath` function I have currently just looks like:

```ts
import * as path from 'path';

export function getPath(): string {
        return path.join(__dirname, 'debugAdapter.js');
}
```

Note that it points to the non-bundled version, but it could point to the bundled version instead.

**Comment by dschaefer** [comment]
My main objective with all build systems I work with is to keep them simple so the next person that comes along can understand them. Seems like a lot of complexity to avoid compiling a single line function that probably takes milliseconds. No?

Can this be fixed by calling the bundled version debugAdapter.js too? We should probably call them the same anyway.

**Comment by simark** [comment]
> My main objective with all build systems I work with is to keep them simple so the next person that comes along can understand them.

Same for me, maybe we just disagree on what is simpler :).  To me, having separate tools that do one thing each makes it easier to understand.  I find it easier when you are able to see the intermediary states, compared to a single tool with plugins that applies multiples transformations, and where you can't see what happens in the middle of the pipeline.

> Seems like a lot of complexity to avoid compiling a single line function that probably takes milliseconds. No?

My point wasn't that it's a problem that this function ends up in the adapter bundle, but rather that it must be emitted in its own separate .js file.  This separate js file will by imported by the user application, which will call `getPath` to get the path of the debug adapter binary.

But as you mentioned, maybe it's possible to build different bundles within the same webpack config, then it would be orthogonal to the use tsc+webpack or just webpack question.

**Comment by dschaefer** [comment]
I sense you're actually afraid of webpack given you're last question :). That's why we picked it, because it can do multiple bundles. For vscode, that enables us to use a single tool invocation to build the extension, the debug adapter and multiple webviews, including bundling common code used by the different webviews, all nicely minimized. And especially nice during development where a single webpack --watch keeps them all updated as you edit the code.

Now, for this project, such bundling isn't strictly necessary. I'm happy to switch to a simple tsc call and see how things develop before we actually need to do a release of this thing. That will unblock your scenario and still keep the build pretty simple.

**Comment by simark** [comment]
> I sense you're actually afraid of webpack given you're last question :).

Haha, "afraid" is perhaps a bit strong.  Like I said, I like the one tool one job philosophy :).

> That's why we picked it, because it can do multiple bundles. For vscode, that enables us to use a single tool invocation to build the extension, the debug adapter and multiple webviews, including bundling common code used by the different webviews, all nicely minimized.

We can still do that with separate tsc and webpack invocations.

> And especially nice during development where a single webpack --watch keeps them all updated as you edit the code.

As you can see in #8, `npm run watch` still achieves that goal.

**Comment by dschaefer** [comment]
Either way, we'll dump webpack for now.

As for #8, my watch is literally 'webpack --watch'. Yours scares me :).

**Comment by simark** [comment]
> As for #8, my watch is literally 'webpack --watch'. Yours scares me :).

I agree it looks a bit scary, but it boils down to `tsc --watch` plus `webpack --watch`.

**Comment by dschaefer** [comment]
webpack is now production only.
